"""Introduce buses

Revision ID: c660ba7047b6
Revises: 1a31ce608336
Create Date: 2025-12-07 14:29:16.623993

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c660ba7047b6'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('item', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('item', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('item', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.add_column('item', sa.Column('bus_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'item', 'bus', ['bus_id'], ['id'])
    op.drop_column('item', 'title')
    op.drop_column('item', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'bus_id')
    op.drop_column('item', 'timestamp')
    op.drop_column('item', 'longitude')
    op.drop_column('item', 'latitude')
    op.drop_table('bus')
    # ### end Alembic commands ###